function app = launchDataVariableConfigApp()
%launchDataVariableConfigApp Open the modern data-variable config app.

    repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    addpath(repoRoot)

    if exist('WidgetTable', 'class') ~= 8
        error(['WidgetTable is required. Install dependencies from ', ...
            'requirements.txt or add WidgetTable/widget_table to the MATLAB path.'])
    end

    nwbConfigurationData = createNwbTestConfiguration();
    nwbConfigurationData.AllVariableNames = { ...
        'Eeg', ...
        'LineScan', ...
        'WheelData', ...
        'PupilDiameter', ...
        'LickEvents'};

    configFilePath = fullfile(tempdir, 'nwbDataVariableConfigAppSmoke.json');
    nansen.module.nwb.config.saveConfiguration( ...
        nansen.module.nwb.config.NwbFileConfiguration.fromStruct(nwbConfigurationData), ...
        string(configFilePath))

    app = nansen.module.nwb.gui.uifigure.DataVariableConfigApp( ...
        nwbConfigurationData, ...
        'FilePath', string(configFilePath));

    fprintf('Opened modern data variable configurator using %s\n', configFilePath)
end
