function filePath = runStandaloneNwbConversionExample()
%runStandaloneNwbConversionExample Run the standalone NWB conversion core.

    repoRoot = fileparts(fileparts(fileparts(mfilename('fullpath'))));
    addpath(genpath(repoRoot))

    assert(exist('NwbFile', 'class') == 8, ...
        ['MatNWB must be on the MATLAB path before running this example. ', ...
        'Add your MatNWB checkout with addpath(genpath(matnwbRoot)).'])

    filePath = fullfile(tempdir, 'nansen-nwb-standalone-example.nwb');
    if isfile(filePath)
        delete(filePath)
    end

    sessionMetadata = struct( ...
        'session_description', 'Standalone NANSEN-NWB example', ...
        'identifier', 'standalone-example', ...
        'session_start_time', datetime(2026, 5, 10, 'TimeZone', 'UTC'));

    behavior = timetable( ...
        seconds((0:4)'), ...
        [0; 3; 7; 4; 1], ...
        'VariableNames', {'speed'});

    dataItem = nansen.module.nwb.config.NwbDataItemConfig( ...
        'VariableName', 'behavior', ...
        'NWBVariableName', 'BehaviorSpeed', ...
        'ConverterName', 'TimetableTimeSeries', ...
        'TargetNwbType', 'TimeSeries', ...
        'PrimaryGroup', 'Acquisition', ...
        'Metadata', struct('data_unit', 'cm/s'));

    config = nansen.module.nwb.config.NwbFileConfiguration( ...
        'OutputPath', filePath, ...
        'SessionMetadata', sessionMetadata, ...
        'DataItems', dataItem);

    converter = nansen.module.nwb.conversion.NwbFileConverter( ...
        config, 'DataResolver', @(variableName) behavior);
    filePath = converter.convert();

    fprintf('Standalone example wrote "%s"\n', filePath)
end
