function nwbFilePath = runStandaloneConversionExample(outputFolder)
%runStandaloneConversionExample - Convert to NWB without a NANSEN session
%   nwbFilePath = runStandaloneConversionExample() builds a conversion
%   configuration by hand, converts made-up data through it, and returns
%   the path of the NWB file it wrote. The file is written to a temporary
%   folder.
%
%   nwbFilePath = runStandaloneConversionExample(outputFolder) writes the
%   file to outputFolder instead.
%
%   The example exists to show that the conversion core has no NANSEN
%   dependency: it takes a configuration and a way to get data, and
%   produces an NWB file. Anyone with matnwb can use it the same way.
%
%   Run it after changing the conversion core, as a check that the whole
%   path still works end to end.
%
%   Example:
%       nwbFilePath = tests.manual.runStandaloneConversionExample();
%       nwbRead(nwbFilePath)
%
%   See also nansen.module.nwb.conversion.NWBFileConverter,
%   nansen.module.nwb.config.NWBFileConfiguration

    arguments
        outputFolder (1,1) string = string(tempname())
    end

    import nansen.module.nwb.config.NWBFileConfiguration
    import nansen.module.nwb.config.NWBDataItemConfig

    if ~isfolder(outputFolder)
        mkdir(outputFolder)
    end
    nwbFilePath = fullfile(outputFolder, "sub-mouse01_ses-demo.nwb");

    % The data a real caller would load from wherever it lives. Here it is
    % a struct the resolver looks names up in.
    variables = struct( ...
        "runningSpeed", timetable(seconds((0:99)'), rand(100, 1), ...
            VariableNames="speed"), ...
        "trials", timetable(seconds((0:10:90)'), seconds((5:10:95)'), ...
            repmat(["go"; "nogo"], 5, 1), VariableNames=["stopTime", "trialType"]), ...
        "fovImages", struct("average", rand(128, 128), "maximum", rand(128, 128)));

    config = NWBFileConfiguration( ...
        OutputPath=nwbFilePath, ...
        SessionMetadata=struct( ...
            "session_description", "Standalone conversion example", ...
            "identifier", "standalone-demo-001", ...
            "session_start_time", datetime("now", TimeZone="local")), ...
        SubjectMetadata=struct( ...
            "subject_id", "mouse01", ...
            "species", "Mus musculus", ...
            "sex", "M", ...
            "age", "P90D"), ...
        GeneralMetadata=struct( ...
            "institution", "Example University", ...
            "lab", "Example Lab"), ...
        DataItems=[ ...
            NWBDataItemConfig( ...
                VariableName="runningSpeed", ...
                NWBVariableName="RunningSpeed", ...
                ConverterName="TimetableTimeSeries", ...
                Metadata=struct("data_unit", "cm/s", ...
                    "description", "Running speed on a treadmill")), ...
            NWBDataItemConfig( ...
                VariableName="trials", ...
                NWBVariableName="trials", ...
                ConverterName="TimetableTimeIntervals", ...
                PrimaryGroup="Intervals", ...
                ConverterArgs=struct("StopTimeVariable", "stopTime")), ...
            NWBDataItemConfig( ...
                VariableName="fovImages", ...
                ConverterName="ProjectionImages", ...
                PrimaryGroup="Processing", ...
                NWBModule="ophys")]);

    converter = nansen.module.nwb.conversion.NWBFileConverter(config, ...
        DataResolver=variables);

    nwbFilePath = converter.convert();

    fprintf("Wrote %s\n", nwbFilePath)
    describeFile(nwbFilePath)
end

function describeFile(nwbFilePath)
%describeFile - Print what ended up in the file

    nwbFile = nwbRead(nwbFilePath);

    fprintf("  identifier      : %s\n", nwbFile.identifier)
    fprintf("  subject         : %s\n", nwbFile.general_subject.subject_id)
    fprintf("  acquisition     : %s\n", ...
        strjoin(string(nwbFile.acquisition.keys()), ", "))

    if ~isempty(nwbFile.intervals_trials)
        fprintf("  trials          : %d rows\n", ...
            numel(loadValues(nwbFile.intervals_trials.start_time)))
    end

    if nwbFile.processing.isKey("ophys")
        fprintf("  ophys module    : %s\n", strjoin(string( ...
            nwbFile.processing.get("ophys").nwbdatainterface.keys()), ", "))
    end

    createDates = loadValues(nwbFile.file_create_date);
    fprintf("  times exported  : %d\n", numel(createDates))
end

function values = loadValues(value)
%loadValues - Read a value whether or not it is still a stub

    if isa(value, "types.hdmf_common.VectorData")
        value = value.data;
    end

    if isa(value, "types.untyped.DataStub")
        values = value.load();
    else
        values = value;
    end
end
