classdef NwbConversionCoreTest < matlab.unittest.TestCase

    methods (Test)
        function jsonConfigurationRoundTripsDataItems(testCase)
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(testCase.getRepoRoot()))
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);

            dataItem = nansen.module.nwb.config.NwbDataItemConfig( ...
                "VariableName", "behavior", ...
                "NWBVariableName", "BehaviorSpeed", ...
                "ConverterName", "TimetableTimeSeries", ...
                "TargetNwbType", "TimeSeries", ...
                "PrimaryGroup", "Acquisition", ...
                "Metadata", struct("data_unit", "cm/s"), ...
                "SourceInfo", struct("DataType", "timetable"));
            config = nansen.module.nwb.config.NwbFileConfiguration( ...
                "OutputPath", fullfile(fixture.Folder, "test.nwb"), ...
                "SessionMetadata", testCase.createSessionMetadata(), ...
                "DataItems", dataItem);

            filePath = fullfile(fixture.Folder, "nwb-config.json");
            nansen.module.nwb.config.saveConfiguration(config, string(filePath))
            loadedConfig = nansen.module.nwb.config.loadConfiguration(string(filePath));

            testCase.verifyEqual(loadedConfig.OutputPath, config.OutputPath)
            testCase.verifyEqual(numel(loadedConfig.DataItems), 1)
            testCase.verifyEqual(loadedConfig.DataItems.VariableName, "behavior")
            testCase.verifyEqual(string(loadedConfig.DataItems.Metadata.data_unit), "cm/s")
        end

        function dataItemConfigAcceptsTableStructOutput(testCase)
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(testCase.getRepoRoot()))

            dataItem = nansen.module.nwb.file.getDefaultFileConfigurationItem();
            dataItem.VariableName = "behavior";
            dataItem.NWBVariableName = "BehaviorSpeed";
            dataItem.Metadata = struct("data_unit", "cm/s");

            dataTable = struct2table(dataItem);
            roundTrippedItem = nansen.module.nwb.config.NwbDataItemConfig.fromStruct( ...
                table2struct(dataTable));

            testCase.verifyEqual(roundTrippedItem.VariableName, "behavior")
            testCase.verifyEqual(roundTrippedItem.Metadata.data_unit, "cm/s")
        end

        function registryRegistersCustomFolder(testCase)
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(testCase.getRepoRoot()))
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);

            converterFile = fullfile(fixture.Folder, "customNwbConverter.m");
            testCase.writeTextFile(converterFile, [
                "function result = customNwbConverter(varargin)" + newline + ...
                "if nargin > 0 && string(varargin{1}) == ""descriptor""" + newline + ...
                "    result = nansen.module.nwb.conversion.NwbConverterDescriptor(" + ...
                """Name"", ""CustomSmoke"", " + ...
                """Source"", ""custom"", " + ...
                """AcceptedTypes"", ""table"", " + ...
                """ProducesNwbType"", ""TimeSeries"", " + ...
                """Function"", @customNwbConverter);" + newline + ...
                "else" + newline + ...
                "    result = varargin{1}.NwbFile;" + newline + ...
                "end" + newline + ...
                "end" + newline])

            registry = nansen.module.nwb.conversion.ConverterRegistry.instance("Refresh", true);
            registry.registerFolder(string(fixture.Folder))

            descriptor = registry.get("CustomSmoke");
            testCase.verifyEqual(descriptor.Source, "custom")
            testCase.verifyEqual(descriptor.ProducesNwbType, "TimeSeries")
        end

        function externalFirstConverterOwnsFileCreation(testCase)
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(testCase.getRepoRoot()))
            fixture = testCase.applyFixture( ...
                matlab.unittest.fixtures.TemporaryFolderFixture);

            descriptor = nansen.module.nwb.conversion.NwbConverterDescriptor( ...
                "Name", "DummyExternalWriter", ...
                "AcceptedTypes", "dummy", ...
                "ProducesNwbType", "*", ...
                "ExecutionMode", "external", ...
                "PlacementPolicy", "converter", ...
                "NeedsData", false, ...
                "Function", @writeDummyExternalFile);
            registry = nansen.module.nwb.conversion.ConverterRegistry();
            registry.add(descriptor)

            dataItem = nansen.module.nwb.config.NwbDataItemConfig( ...
                "VariableName", "external_file", ...
                "ConverterName", "DummyExternalWriter");
            outputPath = fullfile(fixture.Folder, "external-writer.nwb");
            config = nansen.module.nwb.config.NwbFileConfiguration( ...
                "OutputPath", outputPath, ...
                "SessionMetadata", testCase.createSessionMetadata(), ...
                "DataItems", dataItem);

            converter = nansen.module.nwb.conversion.NwbFileConverter( ...
                config, "Registry", registry);
            filePath = converter.convert();

            testCase.verifyTrue(isfile(filePath))
            testCase.verifyEqual(string(fileread(filePath)), "external writer smoke")
        end

        function converterOwnedPlacementDoesNotRequireGroupSelection(testCase)
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture(testCase.getRepoRoot()))

            dataItem = nansen.module.nwb.file.getDefaultFileConfigurationItem();
            dataItem.VariableName = "image_file";
            dataItem.ConverterName = "NeuroConvDataInterface";

            warnings = nansen.module.nwb.file.validateNwbConfiguration(dataItem);

            testCase.verifyEmpty(warnings)
        end
    end

    methods (Static)
        function repoRoot = getRepoRoot()
            repoRoot = fileparts(fileparts(mfilename('fullpath')));
        end

        function metadata = createSessionMetadata()
            metadata = struct( ...
                "session_description", "core test", ...
                "identifier", "core-test", ...
                "session_start_time", datetime(2026, 5, 10, "TimeZone", "UTC"));
        end

        function writeTextFile(filePath, textContent)
            fileId = fopen(filePath, "w");
            cleanupObj = onCleanup(@() fclose(fileId)); %#ok<NASGU>
            fwrite(fileId, char(textContent));
        end
    end
end

function result = writeDummyExternalFile(context)
    fileId = fopen(context.FilePath, "w");
    cleanupObj = onCleanup(@() fclose(fileId)); %#ok<NASGU>
    fwrite(fileId, 'external writer smoke');
    result = struct("DidWriteFile", true, "FilePath", context.FilePath);
end
