classdef ConverterRegistry < handle
%ConverterRegistry Registry for built-in and custom NWB converters.

    properties (Access = private)
        Descriptors
        ConverterFolders (1,:) string = strings(1, 0)
    end

    methods
        function obj = ConverterRegistry()
            obj.Descriptors = containers.Map("KeyType", "char", "ValueType", "any");
            obj.registerBuiltinConverters()
        end

        function add(obj, descriptor)
            descriptor = nansen.module.nwb.conversion.NwbConverterDescriptor.fromAny(descriptor);
            key = char(descriptor.Name);
            if isKey(obj.Descriptors, key)
                error("NansenNwb:DuplicateConverter", ...
                    "Converter '%s' is already registered.", descriptor.Name)
            end

            obj.assertUniqueDisplayName(descriptor)
            obj.Descriptors(key) = descriptor;
        end

        function descriptor = get(obj, converterName)
            converterName = string(converterName);
            if converterName == "" || ismissing(converterName)
                error("NansenNwb:MissingConverter", ...
                    "A converter name must be specified.")
            end

            key = char(converterName);
            if ~isKey(obj.Descriptors, key)
                availableNames = string(keys(obj.Descriptors));
                error("NansenNwb:UnknownConverter", ...
                    "Unknown NWB converter '%s'. Available converters: %s", ...
                    converterName, strjoin(sort(availableNames), ", "))
            end

            descriptor = obj.Descriptors(key);
        end

        function descriptors = list(obj)
            descriptorCells = values(obj.Descriptors);
            if isempty(descriptorCells)
                descriptors = nansen.module.nwb.conversion.NwbConverterDescriptor.empty(0, 1);
            else
                descriptors = [descriptorCells{:}]';
            end
        end

        function names = names(obj)
            names = sort(string(keys(obj.Descriptors)));
        end

        function descriptors = findByAcceptedType(obj, dataType)
            allDescriptors = obj.list();
            isMatch = false(size(allDescriptors));
            for i = 1:numel(allDescriptors)
                isMatch(i) = obj.matchesAcceptedType(allDescriptors(i), dataType);
            end
            descriptors = allDescriptors(isMatch);
        end

        function descriptors = findByDataType(obj, dataType)
            descriptors = obj.findByAcceptedType(dataType);
        end

        function descriptors = findByNwbType(obj, nwbType)
            allDescriptors = obj.list();
            nwbType = string(nwbType);
            isMatch = false(size(allDescriptors));
            for i = 1:numel(allDescriptors)
                producedType = allDescriptors(i).ProducesNwbType;
                isMatch(i) = producedType == "*" || producedType == nwbType;
            end
            descriptors = allDescriptors(isMatch);
        end

        function descriptors = findByNwbModule(obj, moduleName)
            allDescriptors = obj.list();
            moduleName = lower(string(moduleName));
            isMatch = false(size(allDescriptors));
            for i = 1:numel(allDescriptors)
                tags = lower(string(allDescriptors(i).NwbModuleTags));
                isMatch(i) = isempty(tags) || any(tags == "*" | tags == moduleName);
            end
            descriptors = allDescriptors(isMatch);
        end

        function descriptors = findForSourceInfo(obj, sourceInfo)
            arguments
                obj
                sourceInfo (1,1) struct
            end

            candidateTypes = obj.getSourceInfoCandidateTypes(sourceInfo);

            if isempty(candidateTypes)
                descriptors = obj.list();
                return
            end

            allDescriptors = obj.list();
            isMatch = false(size(allDescriptors));
            for i = 1:numel(allDescriptors)
                for j = 1:numel(candidateTypes)
                    isMatch(i) = isMatch(i) || ...
                        obj.matchesAcceptedType(allDescriptors(i), candidateTypes(j));
                end
            end
            descriptors = allDescriptors(isMatch);
        end

        function descriptors = findBySourceInfo(obj, sourceInfo)
            descriptors = obj.findForSourceInfo(sourceInfo);
        end

        function registerFolder(obj, folderPath)
            arguments
                obj
                folderPath (1,1) string {mustBeFolder}
            end

            obj.ConverterFolders(end+1) = folderPath;
            addpath(folderPath)

            files = dir(fullfile(folderPath, "*.m"));
            for i = 1:numel(files)
                functionName = erase(string(files(i).name), ".m");
                descriptor = obj.tryLoadCustomDescriptor(functionName);
                if ~isempty(descriptor)
                    obj.add(descriptor)
                end
            end
        end
    end

    methods (Static)
        function registry = instance(options)
            arguments
                options.Refresh (1,1) logical = false
            end

            persistent registryInstance
            if options.Refresh || isempty(registryInstance) || ~isvalid(registryInstance)
                registryInstance = nansen.module.nwb.conversion.ConverterRegistry();
            end
            registry = registryInstance;
        end
    end

    methods (Access = private)
        function registerBuiltinConverters(obj)
            import nansen.module.nwb.conversion.NwbConverterDescriptor

            obj.add(NwbConverterDescriptor( ...
                "Name", "TimetableTimeSeries", ...
                "Description", "Convert each timetable variable to an NWB TimeSeries.", ...
                "AcceptedTypes", ["timetable", "matlab.timetable"], ...
                "ProducesNwbType", "TimeSeries", ...
                "PrimaryGroup", "Acquisition", ...
                "NwbModuleTags", ["behavior", "misc"], ...
                "Function", @nansen.module.nwb.conversion.builtin.convertTimetableToTimeSeries))

            obj.add(NwbConverterDescriptor( ...
                "Name", "GenericMatNwbType", ...
                "Description", "Create a configured MatNWB neurodata type and place it in the configured group.", ...
                "AcceptedTypes", "*", ...
                "ProducesNwbType", "*", ...
                "PrimaryGroup", "Acquisition", ...
                "NwbModuleTags", "*", ...
                "Function", @nansen.module.nwb.conversion.builtin.convertGenericMatNwbType))

            obj.add(NwbConverterDescriptor( ...
                "Name", "TwoPhotonImageStack", ...
                "Description", "Export a NANSEN ImageStack as a two-photon image series.", ...
                "AcceptedTypes", ["nansen.stack.ImageStack", "ImageStack", "imagestack.ImageStack"], ...
                "ProducesNwbType", "TwoPhotonSeries", ...
                "PrimaryGroup", "Acquisition", ...
                "NwbModuleTags", "ophys", ...
                "ExecutionMode", "external", ...
                "PlacementPolicy", "converter", ...
                "Function", @nansen.module.nwb.conversion.builtin.convertImageStackToTwoPhotonSeries))

            obj.add(NwbConverterDescriptor( ...
                "Name", "NeuroConvDataInterface", ...
                "DisplayName", "Advanced: raw NeuroConv interface", ...
                "Source", "neuroconv", ...
                "Description", "Run one NeuroConv data interface through MATLAB py.*.", ...
                "AcceptedTypes", ["neuroconv", "external-file"], ...
                "ProducesNwbType", "*", ...
                "PrimaryGroup", "Acquisition", ...
                "NwbModuleTags", "*", ...
                "ExecutionMode", "external", ...
                "PlacementPolicy", "converter", ...
                "RequiresPython", true, ...
                "NeedsData", false, ...
                "Function", @nansen.module.nwb.conversion.builtin.convertWithNeuroconv))

            obj.add(NwbConverterDescriptor( ...
                "Name", "NeuroConvImageInterface", ...
                "DisplayName", "NeuroConv: image sequence", ...
                "Source", "neuroconv", ...
                "Description", "Run NeuroConv ImageInterface using the selected variable's data file.", ...
                "AcceptedTypes", ["external-file", "image", "image-sequence"], ...
                "ProducesNwbType", "Images", ...
                "PrimaryGroup", "Acquisition", ...
                "NwbModuleTags", "ophys", ...
                "ExecutionMode", "external", ...
                "PlacementPolicy", "converter", ...
                "RequiresPython", true, ...
                "NeedsData", false, ...
                "DefaultConverterArgs", struct( ...
                    "InterfaceClassName", "ImageInterface", ...
                    "SourceArgumentName", "file_paths", ...
                    "SourcePathMode", "fileList"), ...
                "Function", @nansen.module.nwb.conversion.builtin.convertWithNeuroconv))

            obj.add(NwbConverterDescriptor( ...
                "Name", "NeuroConvTiffImagingInterface", ...
                "DisplayName", "NeuroConv: TIFF imaging", ...
                "Source", "neuroconv", ...
                "Description", "Run NeuroConv TiffImagingInterface using the selected variable's data file.", ...
                "AcceptedTypes", ["external-file", "tif", "tiff"], ...
                "ProducesNwbType", "TwoPhotonSeries", ...
                "PrimaryGroup", "Acquisition", ...
                "NwbModuleTags", "ophys", ...
                "ExecutionMode", "external", ...
                "PlacementPolicy", "converter", ...
                "RequiresPython", true, ...
                "NeedsData", false, ...
                "DefaultConverterArgs", struct( ...
                    "InterfaceClassName", "TiffImagingInterface", ...
                    "SourceArgumentName", "file_path", ...
                    "SourcePathMode", "file"), ...
                "Function", @nansen.module.nwb.conversion.builtin.convertWithNeuroconv))

            obj.add(NwbConverterDescriptor( ...
                "Name", "NeuroConvScanImageImagingInterface", ...
                "DisplayName", "NeuroConv: ScanImage imaging", ...
                "Source", "neuroconv", ...
                "Description", "Run NeuroConv ScanImageImagingInterface using the selected variable's data file.", ...
                "AcceptedTypes", ["external-file", "scanimage", "tif", "tiff"], ...
                "ProducesNwbType", "TwoPhotonSeries", ...
                "PrimaryGroup", "Acquisition", ...
                "NwbModuleTags", "ophys", ...
                "ExecutionMode", "external", ...
                "PlacementPolicy", "converter", ...
                "RequiresPython", true, ...
                "NeedsData", false, ...
                "DefaultConverterArgs", struct( ...
                    "InterfaceClassName", "ScanImageImagingInterface", ...
                    "SourceArgumentName", "file_path", ...
                    "SourcePathMode", "file"), ...
                "Function", @nansen.module.nwb.conversion.builtin.convertWithNeuroconv))

            obj.add(NwbConverterDescriptor( ...
                "Name", "NeuroConvSuite2pSegmentationInterface", ...
                "DisplayName", "NeuroConv: Suite2p segmentation", ...
                "Source", "neuroconv", ...
                "Description", "Run NeuroConv Suite2pSegmentationInterface using the selected variable's parent folder.", ...
                "AcceptedTypes", ["external-file", "suite2p", "suite2p.rois"], ...
                "ProducesNwbType", "PlaneSegmentation", ...
                "PrimaryGroup", "Processing", ...
                "NwbModuleTags", "ophys", ...
                "ExecutionMode", "external", ...
                "PlacementPolicy", "converter", ...
                "RequiresPython", true, ...
                "NeedsData", false, ...
                "DefaultConverterArgs", struct( ...
                    "InterfaceClassName", "Suite2pSegmentationInterface", ...
                    "SourceArgumentName", "folder_path", ...
                    "SourcePathMode", "parentFolder"), ...
                "Function", @nansen.module.nwb.conversion.builtin.convertWithNeuroconv))

            obj.add(NwbConverterDescriptor( ...
                "Name", "NeuroConvDeepLabCutInterface", ...
                "DisplayName", "NeuroConv: DeepLabCut pose", ...
                "Source", "neuroconv", ...
                "Description", "Run NeuroConv DeepLabCutInterface using the selected variable's data file.", ...
                "AcceptedTypes", ["external-file", "deeplabcut", "dlc"], ...
                "ProducesNwbType", "PoseEstimation", ...
                "PrimaryGroup", "Processing", ...
                "NwbModuleTags", "behavior", ...
                "ExecutionMode", "external", ...
                "PlacementPolicy", "converter", ...
                "RequiresPython", true, ...
                "NeedsData", false, ...
                "DefaultConverterArgs", struct( ...
                    "InterfaceClassName", "DeepLabCutInterface", ...
                    "SourceArgumentName", "file_path", ...
                    "SourcePathMode", "file"), ...
                "Function", @nansen.module.nwb.conversion.builtin.convertWithNeuroconv))

            obj.add(NwbConverterDescriptor( ...
                "Name", "RoiGroupPlaneSegmentation", ...
                "Description", "Convert an ROI group to NWB PlaneSegmentation in the ophys processing module.", ...
                "AcceptedTypes", ["RoiGroup", "nansen.roi.RoiGroup", "suite2p.rois"], ...
                "ProducesNwbType", "PlaneSegmentation", ...
                "PrimaryGroup", "Processing", ...
                "NwbModuleTags", "ophys", ...
                "PlacementPolicy", "converter", ...
                "Function", @nansen.module.nwb.conversion.builtin.convertRoiGroupToPlaneSegmentation))

            obj.add(NwbConverterDescriptor( ...
                "Name", "RoiSignals", ...
                "Description", "Convert ROI signal arrays to NWB RoiResponseSeries.", ...
                "AcceptedTypes", ["RoiSignals", "suite2p.roisignals"], ...
                "ProducesNwbType", "RoiResponseSeries", ...
                "PrimaryGroup", "Processing", ...
                "NwbModuleTags", "ophys", ...
                "PlacementPolicy", "converter", ...
                "Function", @nansen.module.nwb.conversion.builtin.convertRoiSignals))
        end

        function descriptor = tryLoadCustomDescriptor(~, functionName)
            descriptor = [];
            try
                descriptor = feval(functionName, "descriptor");
            catch
                try
                    descriptor = feval(functionName);
                catch
                    descriptor = [];
                end
            end

            if ~isempty(descriptor) && ...
                    ~(isa(descriptor, "nansen.module.nwb.conversion.NwbConverterDescriptor") || isstruct(descriptor))
                descriptor = [];
            end
        end

        function assertUniqueDisplayName(obj, descriptor)
            descriptorCells = values(obj.Descriptors);
            for i = 1:numel(descriptorCells)
                existingDescriptor = descriptorCells{i};
                if existingDescriptor.DisplayName == descriptor.DisplayName
                    error("NansenNwb:DuplicateConverterDisplayName", ...
                        "Converter display name '%s' is already registered by '%s'.", ...
                        descriptor.DisplayName, existingDescriptor.Name)
                end
            end
        end
    end

    methods (Static, Access = private)
        function tf = matchesAcceptedType(descriptor, dataType)
            acceptedTypes = nansen.module.nwb.conversion.ConverterRegistry.normalizeMatchText( ...
                descriptor.AcceptedTypes);
            dataType = nansen.module.nwb.conversion.ConverterRegistry.normalizeMatchText(dataType);
            tf = any(acceptedTypes == "*" | acceptedTypes == dataType);
        end

        function candidateTypes = getSourceInfoCandidateTypes(sourceInfo)
            candidateTypes = strings(1, 0);
            sourceFields = ["DataType", "ClassName", "Format", "SourceFormat", ...
                "Modality", "FileExtension"];
            for i = 1:numel(sourceFields)
                fieldName = char(sourceFields(i));
                if isfield(sourceInfo, fieldName) && ~isempty(sourceInfo.(fieldName))
                    candidateTypes = [candidateTypes, string(sourceInfo.(fieldName))]; %#ok<AGROW>
                end
            end

            pathFields = ["Path", "FilePath"];
            for i = 1:numel(pathFields)
                fieldName = char(pathFields(i));
                if isfield(sourceInfo, fieldName) && ~isempty(sourceInfo.(fieldName))
                    [~, ~, extension] = fileparts(string(sourceInfo.(fieldName)));
                    if extension ~= ""
                        candidateTypes = [candidateTypes, extension]; %#ok<AGROW>
                    end
                end
            end

            candidateTypes = nansen.module.nwb.conversion.ConverterRegistry.normalizeMatchText( ...
                candidateTypes);
            candidateTypes = unique(candidateTypes(candidateTypes ~= ""), "stable");
        end

        function values = normalizeMatchText(values)
            values = lower(strtrim(string(values)));
            values = erase(values, ".");
            values = values(values ~= "" & ~ismissing(values));
        end
    end
end
